services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "7860:7860"
    environment:
      - HOST=0.0.0.0
      - PORT=7860
    env_file:
      - .env
    command: python -m src.main